### ISSUE TITLE
404 page for the fisrt tutorial doc: High availability volumes/node failover

### ISSUE THREAD

**Issue by walidshaari** [storageos/tutorials#15]
the first link under tutorials gives 404, "High availability volumes/node failover" is pointing to https://docs.storageos.com/docs/manage/features/replication, however, the page doe not exist.  should it be https://docs.storageos.com/docs/manage/features/high-availability ?

**Comment by oicheryl** [comment]
Hi walidshaari, I've fixed the broken link.

Thanks for reporting!
